using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Winch.Core;

namespace ArchipelagoDredge.Game.Helpers;

public class ItemHelper
{
}

[SuppressMessage("ReSharper", "InconsistentNaming")]
public enum Item
{
    MESSAGE_FISHERMAN_1,
    MESSAGE_1,
    MESSAGE_10,
    MESSAGE_2,
    MESSAGE_3,
    MESSAGE_4,
    MESSAGE_5,
    MESSAGE_6,
    MESSAGE_7,
    MESSAGE_8,
    MESSAGE_9,
    MESSAGE_TPR_1,
    MESSAGE_TPR_2,
    MESSAGE_TPR_3,
    MESSAGE_TPR_4,
    MESSAGE_TPR_5,
    MESSAGE_TPR_6,
    MESSAGE_TPR_7,
    MESSAGE_TPR_8,
    MESSAGE_TPR_9,
    MESSAGE_OLD_MAYOR_1,
    BOOK_ABERRATION_1,
    BOOK_BARTER_1,
    BOOK_BARTER_2,
    BOOK_ECOLOGY_1,
    BOOK_ECOLOGY_2,
    BOOK_EQUIP_1,
    BOOK_EQUIP_2,
    BOOK_FISHING_1,
    BOOK_FISHING_2,
    BOOK_SPEED_1,
    BOOK_SPEED_2,
    BOOK_SANITY_1,
    BOOK_SANITY_2,
    BAIT,
    BAIT_AB,
    BAIT_CRAB,
    BAIT_EXOTIC,
    CANISTER,
    DMG,
    DARK_SPLASH,
    DREDGE1,
    ENGINE1,
    ENGINE10,
    ENGINE2,
    ENGINE3,
    ENGINE4,
    ENGINE5,
    ENGINE6,
    ENGINE7,
    ENGINE8,
    ENGINE9,
    LIGHT1,
    LIGHT2,
    LIGHT3,
    LIGHT4,
    LIGHT5,
    LIGHT6,
    NET1,
    NET2,
    NET3,
    NET4,
    NET5,
    NET6,
    NET7,
    NET8,
    TIR_NET1,
    TIR_NET2,
    POT1,
    POT2,
    POT3,
    POT4,
    POT5,
    POT6,
    POT7,
    POT8,
    TIR_POT1,
    ROD1,
    ROD11,
    ROD12,
    ROD13,
    ROD14,
    ROD15,
    ROD16,
    ROD17,
    ROD18,
    ROD19,
    ROD2,
    ROD20,
    ROD21,
    ROD22,
    ROD23,
    ROD3,
    ROD4,
    ROD5,
    ROD6,
    ROD8,
    TIR_ROD1,
    TIR_ROD2,
    TIR_ROD3,
    TIR_ROD4,
    TIR_ROD5,
    EXPLOSIVES,
    ANCHOVY_AB_1,
    ANCHOVY,
    ANGLERFISH_AB_1,
    ANGLERFISH,
    SQUID_AB_1,
    SQUID_AB_2,
    SQUID,
    AURORA_JELLYFISH_AB_1,
    AURORA_JELLYFISH,
    BARRACUDA_AB_1,
    BARRACUDA_AB_2,
    BARRACUDA,
    BARRELEYE_AB_1,
    BARRELEYE,
    BLACK_GROUPER_AB_1,
    BLACK_GROUPER_AB_2,
    BLACK_GROUPER,
    BLACK_SEA_BASS_AB_1,
    BLACK_SEA_BASS,
    BLACKFIN_TUNA_AB_1,
    BLACKFIN_TUNA,
    BLACKMOUTH_SALMON_AB_1,
    BLACKMOUTH_SALMON,
    BLACKTIP_REEF_SHARK_AB_1,
    BLACKTIP_REEF_SHARK,
    MACKEREL,
    BRONZE_WHALER_AB_1,
    BRONZE_WHALER,
    CATFISH_AB_1,
    CATFISH,
    COD_AB_1,
    COD_AB_2,
    COD_AB_3,
    COD,
    COELACANTH,
    CONGER_EEL_AB_1,
    CONGER_EEL,
    CORAL_GROUPER_AB_1,
    CORAL_GROUPER,
    BLUE_CRAB_AB_1,
    BLUE_CRAB,
    CRAB_AB_1,
    CRAB,
    CROWN_OF_THORNS_AB_1,
    CROWN_OF_THORNS,
    DECORATOR_CRAB_AB_1,
    DECORATOR_CRAB,
    FIDDLER_CRAB_AB_1,
    FIDDLER_CRAB,
    GIANT_MUD_CRAB_AB_1,
    GIANT_MUD_CRAB,
    HORSESHOE_CRAB_AB_1,
    HORSESHOE_CRAB,
    ROCK_CRAB_AB_1,
    ROCK_CRAB,
    SPIDER_CRAB_AB_1,
    SPIDER_CRAB,
    SPINY_LOBSTER_AB_1,
    SPINY_LOBSTER,
    SQUAT_LOBSTER_AB_1,
    SQUAT_LOBSTER,
    VOLCANO_SNAIL_AB_1,
    VOLCANO_SNAIL,
    CUSK_EEL_AB_1,
    CUSK_EEL,
    DEVIL_RAY_AB_1,
    DEVIL_RAY,
    CHAR_AB_1,
    CHAR,
    COLOSSAL_SQUID_AB_1,
    COLOSSAL_SQUID,
    GOBLIN_SHARK_AB_1,
    GOBLIN_SHARK,
    ICEFISH_AB_1,
    ICEFISH_AB_2,
    ICEFISH_AB_3,
    ICEFISH,
    KING_CRAB_AB_1,
    KING_CRAB,
    LIZARDFISH_AB_1,
    LIZARDFISH,
    SEA_STARS_AB_1,
    SEA_STARS,
    SLEEPER_SHARK,
    STARGAZER_AB_1,
    STARGAZER,
    TOOTHFISH_AB_1,
    TOOTHFISH,
    WOLFFISH_AB_1,
    WOLFFISH,
    ABYSSAL_GAR_AB_1,
    ABYSSAL_GAR,
    ARAPAIMA_AB_1,
    ARAPAIMA,
    BOREASPIS_AB_1,
    BOREASPIS,
    COELACANTH_AB_1,
    DEEP_FORM_AB_1,
    DUNKLEOSTEUS_AB_1,
    DUNKLEOSTEUS,
    EAGLE_SHARK_AB_1,
    EAGLE_SHARK,
    GIANT_DRAGONFISH_AB_1,
    GIANT_DRAGONFISH,
    GOLIATH_TIGERFISH_AB_1,
    GULPER_EEL_AB_1,
    KERYGMACHELA_AB_1,
    KERYGMACHELA,
    LANCETFISH_AB_1,
    LANCETFISH,
    MAHI_MAHI_AB_1,
    MAHI_MAHI,
    NAUTILUS_AB_1,
    NAUTILUS,
    NIPPONITES_AB_1,
    NIPPONITES,
    OARFISH_AB_1,
    OPABINIA_AB_1,
    OPABINIA,
    OSTEOSTRACAN_AB_1,
    OSTEOSTRACAN,
    PADDLEFISH_AB_1,
    PADDLEFISH,
    SAWFISH_AB_1,
    SAWFISH,
    SEA_CUCUMBER_AB_1,
    SEA_CUCUMBER,
    SEA_SCORPION_AB_1,
    SEA_SCORPION,
    SEA_SLUG_AB_1,
    SEA_SLUG,
    SLEEPER_SHARK_AB_1,
    SOLLASINA_AB_1,
    SOLLASINA,
    SWORDFISH_AB_1,
    SWORDFISH,
    TRILOBITE_AB_1,
    TRILOBITE,
    TRIPOD_SPIDERFISH_AB_1,
    TRIPOD_SPIDERFISH,
    TULLIMONSTRUM_AB_1,
    TULLIMONSTRUM,
    VETULICOLIA_AB_1,
    VETULICOLIA,
    XIPHACTINUS_AB_1,
    XIPHACTINUS,
    FANGTOOTH_AB_1,
    FANGTOOTH,
    FIREFLY_SQUID_AB_1,
    FIREFLY_SQUID,
    FRILLED_SHARK_AB_1,
    FRILLED_SHARK,
    GAR_AB_1,
    GAR_AB_2,
    GAR,
    GHOST_SHARK_AB_1,
    GHOST_SHARK,
    GIANT_AMPHIPOD_AB_1,
    GIANT_AMPHIPOD,
    GLOWING_OCTOPUS_AB_1,
    GLOWING_OCTOPUS,
    GOLIATH_TIGERFISH,
    EEL_AB_1,
    EEL_AB_2,
    EEL,
    GREY_MULLET_AB_1,
    GREY_MULLET_AB_2,
    GREY_MULLET,
    FLOUNDER_AB_1,
    FLOUNDER_AB_2,
    FLOUNDER,
    GULPER_EEL,
    HAMMERHEAD_SHARK_AB_1,
    HAMMERHEAD_SHARK,
    LONGFIN_EEL_AB_1,
    LONGFIN_EEL,
    STOPLIGHT_LOOSEJAW_AB_1,
    STOPLIGHT_LOOSEJAW,
    MACKEREL_AB_1,
    MACKEREL_AB_2,
    MACKEREL_AB_3,
    MOONFISH_AB_1,
    MOONFISH_AB_2,
    MOONFISH,
    OARFISH,
    OCEANIC_PERCH_AB_1,
    OCEANIC_PERCH,
    PALE_SKATE_AB_1,
    PALE_SKATE,
    RATTAIL_AB_1,
    RATTAIL,
    RED_SNAPPER_AB_1,
    RED_SNAPPER_AB_2,
    RED_SNAPPER,
    SAILFISH_AB_1,
    SAILFISH_AB_2,
    SAILFISH,
    SCARLET_PRAWN_AB_1,
    SCARLET_PRAWN,
    SEAROBIN_AB_1,
    SEAROBIN,
    SERGEANT_FISH_AB_1,
    SERGEANT_FISH,
    SNAILFISH_AB_1,
    SNAILFISH_AB_2,
    SNAILFISH,
    SNAKE_MACKEREL_AB_1,
    SNAKE_MACKEREL_AB_2,
    SNAKE_MACKEREL,
    STINGRAY_AB_1,
    STINGRAY,
    STONEFISH_AB_1,
    STONEFISH_AB_2,
    STONEFISH,
    STURGEON_AB_1,
    STURGEON,
    SUNFISH_AB_1,
    SUNFISH_AB_2,
    SUNFISH,
    TARPON_AB_1,
    TARPON,
    TIGER_MACKEREL_AB_1,
    TIGER_MACKEREL_AB_2,
    TIGER_MACKEREL,
    VIPERFISH_AB_1,
    VIPERFISH_AB_2,
    VIPERFISH,
    WRECKFISH_AB_1,
    WRECKFISH_AB_2,
    WRECKFISH,
    FLAG_1,
    FLAG_2,
    FLAG_3,
    FLAG_4,
    FLAG_5,
    FLAG_6,
    FLAG_7,
    GADGET_1,
    GADGET_2,
    GADGET_3,
    GADGET_4,
    GADGET_5,
    GADGET_6,
    ICE_BLOCK_1,
    ICE_BLOCK_2,
    CLOTH,
    CRATE,
    LUMBER,
    METAL,
    RESEARCH_ITEM,
    SCRAP,
    QUEST_BELT_BUCKLE,
    QUEST_BUILDER,
    QUEST_CAMERA_CASE,
    QUEST_CASTAWAY,
    QUEST_COMPONENTS,
    QUEST_CORPSE,
    QUEST_DOG_TAG,
    QUEST_DOG,
    QUEST_CREST,
    QUEST_FLAME,
    QUEST_HERMIT,
    QUEST_ICE_AXE,
    QUEST_ICEBREAKER_1,
    QUEST_ICEBREAKER_2,
    QUEST_ICEBREAKER_3,
    QUEST_ICE_SHAPER,
    QUEST_ICE_STONE,
    QUEST_MACHINE,
    QUEST_MAP_1,
    QUEST_MAP_2,
    QUEST_MAP_3,
    QUEST_MORTAR_1,
    QUEST_MORTAR_2,
    QUEST_PACKAGE,
    QUEST_PACKAGE_2,
    QUEST_BAIT_1,
    QUEST_BAIT_2,
    QUEST_BAIT_3,
    QUEST_TABLET_1,
    QUEST_TABLET_2,
    QUEST_TABLET_3,
    QUEST_TABLET_4,
    HANDKERCHIEF,
    RELIC1,
    RELIC2,
    RELIC3,
    RELIC4,
    RELIC5,
    REPAIR_BOAT,
    REPAIR_PANIC,
    REPAIR_POT,
    ROT,
    TELEPORT_ANCHOR,
    BAG_DOUBLOON,
    BIG_BAG_DOUBLOON,
    BROKEN_MONOCLE,
    BROKEN_SPECTACLES,
    DOUBLOON,
    EARRING_1,
    EARRING_2,
    EARRING_3,
    EARRING_4,
    EARRING_5,
    FANCY_BOOT,
    GOBLET,
    IRON_CHAIN,
    RING_1,
    RING_2,
    RING_3,
    RING_4,
    RING_5,
    RING_6,
    RING_7,
    SEXTANT,
    SILVER_PLATE,
    SILVER_TRINKET,
    WHOLE_ICEBREAKER,
    PROGRESSIVE_HULL
}

public static class ItemNames
{
    public static Dictionary<Item, string> itemNames = new()
    {
        {Item.MESSAGE_FISHERMAN_1, "Fisherman's Note"},
        {Item.MESSAGE_1, "6th, 7th March 1927"},
        {Item.MESSAGE_10, "Tattered Receipt"},
        {Item.MESSAGE_2, "1st June 1927"},
        {Item.MESSAGE_3, "20th August 1927"},
        {Item.MESSAGE_4, "21st August 1927"},
        {Item.MESSAGE_5, "9th September 1927"},
        {Item.MESSAGE_6, "14th September 1927"},
        {Item.MESSAGE_7, "Message 7 - ???"},
        {Item.MESSAGE_8, "Message 8 - ???"},
        {Item.MESSAGE_9, "Artifact Manifest"},
        {Item.MESSAGE_TPR_1, "Captain's Log - 30th May, 1847"},
        {Item.MESSAGE_TPR_2, "Captain's Log - 1st June, 1847"},
        {Item.MESSAGE_TPR_3, "Captain's Log - 5th June, 1847"},
        {Item.MESSAGE_TPR_4, "Tattered Diary - 2nd June, 1847"},
        {Item.MESSAGE_TPR_5, "Tattered Diary - 4th June, 1847"},
        {Item.MESSAGE_TPR_6, "Tattered Diary - 5th June, 1847"},
        {Item.MESSAGE_TPR_7, "Leather Journal - 4th June, 1847"},
        {Item.MESSAGE_TPR_8, "Leather Journal - 7th June, 1847"},
        {Item.MESSAGE_TPR_9, "Leather Journal - 8th June, 1847"},
        {Item.MESSAGE_OLD_MAYOR_1, "Ragged Note"},
        {Item.BOOK_ABERRATION_1, "Book of Astral Symbols"},
        {Item.BOOK_BARTER_1, "Haggling and Bartering: A Guide"},
        {Item.BOOK_BARTER_2, "Art of the Silver Tongue"},
        {Item.BOOK_ECOLOGY_1, "Sustainable Fishing"},
        {Item.BOOK_ECOLOGY_2, "A Plan For The Future"},
        {Item.BOOK_EQUIP_1, "The Engineer's Companion"},
        {Item.BOOK_EQUIP_2, "Nautical Engineering"},
        {Item.BOOK_FISHING_1, "Rods, Reels and Rigs"},
        {Item.BOOK_FISHING_2, "Advanced Fishing"},
        {Item.BOOK_SPEED_1, "Correct Engine Operation"},
        {Item.BOOK_SPEED_2, "Pushing The Limit: Engines"},
        {Item.BOOK_SANITY_1, "The Relaxed Mind"},
        {Item.BOOK_SANITY_2, "Getting Over It With Mind and Body"},
        {Item.BAIT, "Mixed Bait"},
        {Item.BAIT_AB, "Aberrated Bait"},
        {Item.BAIT_CRAB, "Insta-Crab Bait"},
        {Item.BAIT_EXOTIC, "Exotic Bait"},
        {Item.CANISTER, "Dark Canister"},
        {Item.DMG, "Damage"},
        {Item.DARK_SPLASH, "Dark Splash"},
        {Item.DREDGE1, "Dredge Crane"},
        {Item.ENGINE1, "Starting Gear - Peculiar Engine"},
        {Item.ENGINE10, "Arterial Engine"},
        {Item.ENGINE2, "Rusty Outboard Engine"},
        {Item.ENGINE3, "Improved Outboard Engine"},
        {Item.ENGINE4, "Refined Outboard Engine"},
        {Item.ENGINE5, "Twin Prop Engine"},
        {Item.ENGINE6, "Jet Drive Engine"},
        {Item.ENGINE7, "Twin Jet Drive Engine"},
        {Item.ENGINE8, "Engine Stack"},
        {Item.ENGINE9, "Weak Valve Engine"},
        {Item.LIGHT1, "Cracked Bulb"},
        {Item.LIGHT2, "Cloudy Lens"},
        {Item.LIGHT3, "Halogen Spotlight"},
        {Item.LIGHT4, "Tungsten Floodlight"},
        {Item.LIGHT5, "Incandescent Array"},
        {Item.LIGHT6, "Flame of the Sky"},
        {Item.NET1, "Basic Trawl Net"},
        {Item.NET2, "Improved Trawl Net"},
        {Item.NET3, "Silt Filtering Trawl Net"},
        {Item.NET4, "Tempered Mesh Net"},
        {Item.NET5, "Large Trawl Net"},
        {Item.NET6, "Heavy-Duty Trawl Net"},
        {Item.NET7, "Radiant Trawl Net"},
        {Item.NET8, "Brittle Trawl Net"},
        {Item.TIR_NET1, "Siphon Trawler"},
        {Item.TIR_NET2, "Material Harvester"},
        {Item.POT1, "Basic Crab Pot"},
        {Item.POT2, "Efficient Crab Pot"},
        {Item.POT3, "Hardy Crab Pot"},
        {Item.POT4, "Large Crab Pot"},
        {Item.POT5, "Complex Crab Pot"},
        {Item.POT6, "Massive Crab Pot"},
        {Item.POT7, "Reinforced Crab Pot"},
        {Item.POT8, "Mouth of the Deep"},
        {Item.TIR_POT1, "Flotsam Trap"},
        {Item.ROD1, "Starting Gear - Basic Fishing Pole"},
        {Item.ROD11, "Fathomless Winch"},
        {Item.ROD12, "Heat-Resistant Line"},
        {Item.ROD13, "Anti-Tangle Line"},
        {Item.ROD14, "Versatile Rod"},
        {Item.ROD15, "Harvesting Platform"},
        {Item.ROD16, "Tendon Rod"},
        {Item.ROD17, "Encrusted Talisman"},
        {Item.ROD18, "Simple Skimmer"},
        {Item.ROD19, "Sinew Spindle"},
        {Item.ROD2, "Weighted Line"},
        {Item.ROD20, "Sign of Ruin"},
        {Item.ROD21, "Custom Rod"},
        {Item.ROD22, "Barbed Ice Rod"},
        {Item.ROD23, "Glacial Lance"},
        {Item.ROD3, "Hydraulic Rod"},
        {Item.ROD4, "Flexible Fishing Pole"},
        {Item.ROD5, "Sampling Device"},
        {Item.ROD6, "Bottomless Lines"},
        {Item.ROD8, "Viscera Crane"},
        {Item.TIR_ROD1, "Infused Winch"},
        {Item.TIR_ROD2, "Infused Rod"},
        {Item.TIR_ROD3, "Infused Hoist"},
        {Item.TIR_ROD4, "Infused Fireproof Rod"},
        {Item.TIR_ROD5, "Infused Coiling Rod"},
        {Item.EXPLOSIVES, "Packed Explosives"},
        {Item.ANCHOVY_AB_1, "Anchovy King"},
        {Item.ANCHOVY, "Anchovy"},
        {Item.ANGLERFISH_AB_1, "Bursting Anglerfish"},
        {Item.ANGLERFISH, "Anglerfish"},
        {Item.SQUID_AB_1, "Brood Squid"},
        {Item.SQUID_AB_2, "Snag Squid"},
        {Item.SQUID, "Arrow Squid"},
        {Item.AURORA_JELLYFISH_AB_1, "Parhelion Jellyfish"},
        {Item.AURORA_JELLYFISH, "Aurora Jellyfish"},
        {Item.BARRACUDA_AB_1, "Savage Barracuda"},
        {Item.BARRACUDA_AB_2, "Concertina Barracuda"},
        {Item.BARRACUDA, "Barracuda"},
        {Item.BARRELEYE_AB_1, "Voideye"},
        {Item.BARRELEYE, "Barreleye"},
        {Item.BLACK_GROUPER_AB_1, "Tusked Grouper"},
        {Item.BLACK_GROUPER_AB_2, "Voltaic Grouper"},
        {Item.BLACK_GROUPER, "Black Grouper"},
        {Item.BLACK_SEA_BASS_AB_1, "Scouring Bass"},
        {Item.BLACK_SEA_BASS, "Black Sea Bass"},
        {Item.BLACKFIN_TUNA_AB_1, "Razormouth Tuna"},
        {Item.BLACKFIN_TUNA, "Blackfin Tuna"},
        {Item.BLACKMOUTH_SALMON_AB_1, "Decaying Blackmouth"},
        {Item.BLACKMOUTH_SALMON, "Blackmouth Salmon"},
        {Item.BLACKTIP_REEF_SHARK_AB_1, "Cleft-mouth Shark"},
        {Item.BLACKTIP_REEF_SHARK, "Blacktip Reef Shark"},
        {Item.MACKEREL, "Blue Mackerel"},
        {Item.BRONZE_WHALER_AB_1, "Bloodskin Shark"},
        {Item.BRONZE_WHALER, "Bronze Whaler"},
        {Item.CATFISH_AB_1, "Nightwing Catfish"},
        {Item.CATFISH, "Catfish"},
        {Item.COD_AB_1, "All-Seeing Cod"},
        {Item.COD_AB_2, "Fanged Cod"},
        {Item.COD_AB_3, "Three-Headed Cod"},
        {Item.COD, "Cod"},
        {Item.COELACANTH, "Coelacanth"},
        {Item.CONGER_EEL_AB_1, "Sprouting Eel"},
        {Item.CONGER_EEL, "Conger Eel"},
        {Item.CORAL_GROUPER_AB_1, "Consumed Grouper"},
        {Item.CORAL_GROUPER, "Coral Grouper"},
        {Item.BLUE_CRAB_AB_1, "Entangled Crab"},
        {Item.BLUE_CRAB, "Blue Crab"},
        {Item.CRAB_AB_1, "Cerebral Crab"},
        {Item.CRAB, "Common Crab"},
        {Item.CROWN_OF_THORNS_AB_1, "Crown of Nadir"},
        {Item.CROWN_OF_THORNS, "Crown of Thorns"},
        {Item.DECORATOR_CRAB_AB_1, "Cortex Decorator"},
        {Item.DECORATOR_CRAB, "Decorator Crab"},
        {Item.FIDDLER_CRAB_AB_1, "Malignant Pincer"},
        {Item.FIDDLER_CRAB, "Fiddler Crab"},
        {Item.GIANT_MUD_CRAB_AB_1, "Mire Screecher"},
        {Item.GIANT_MUD_CRAB, "Giant Mud Crab"},
        {Item.HORSESHOE_CRAB_AB_1, "Effigy Crab"},
        {Item.HORSESHOE_CRAB, "Horseshoe Crab"},
        {Item.ROCK_CRAB_AB_1, "Splintered Crab"},
        {Item.ROCK_CRAB, "Rock Crab"},
        {Item.SPIDER_CRAB_AB_1, "Umbral Puppet"},
        {Item.SPIDER_CRAB, "Spider Crab"},
        {Item.SPINY_LOBSTER_AB_1, "Imperious Lobster"},
        {Item.SPINY_LOBSTER, "Spiny Lobster"},
        {Item.SQUAT_LOBSTER_AB_1, "Sable Reacher"},
        {Item.SQUAT_LOBSTER, "Squat Lobster"},
        {Item.VOLCANO_SNAIL_AB_1, "Grasping Snail"},
        {Item.VOLCANO_SNAIL, "Volcano Snail"},
        {Item.CUSK_EEL_AB_1, "Infernal Eel"},
        {Item.CUSK_EEL, "Cusk Eel"},
        {Item.DEVIL_RAY_AB_1, "Withered Ray"},
        {Item.DEVIL_RAY, "Devil Ray"},
        {Item.CHAR_AB_1, "Bubbling Char"},
        {Item.CHAR, "Char"},
        {Item.COLOSSAL_SQUID_AB_1, "Pale Grasper"},
        {Item.COLOSSAL_SQUID, "Colossal Squid"},
        {Item.GOBLIN_SHARK_AB_1, "Grisly Shark"},
        {Item.GOBLIN_SHARK, "Goblin Shark"},
        {Item.ICEFISH_AB_1, "Fractalline Icefish"},
        {Item.ICEFISH_AB_2, "Thawed Icefish"},
        {Item.ICEFISH_AB_3, "Astral Icefish"},
        {Item.ICEFISH, "Icefish"},
        {Item.KING_CRAB_AB_1, "King's Wreath"},
        {Item.KING_CRAB, "King Crab"},
        {Item.LIZARDFISH_AB_1, "Feral Lizardfish"},
        {Item.LIZARDFISH, "Lizardfish"},
        {Item.SEA_STARS_AB_1, "Fallen Stars"},
        {Item.SEA_STARS, "Sea Stars"},
        {Item.SLEEPER_SHARK, "Sleeper Shark"},
        {Item.STARGAZER_AB_1, "Craterous Seer"},
        {Item.STARGAZER, "Stargazer"},
        {Item.TOOTHFISH_AB_1, "Bulbous Toothfish"},
        {Item.TOOTHFISH, "Toothfish"},
        {Item.WOLFFISH_AB_1, "Hinged Wolffish"},
        {Item.WOLFFISH, "Wolffish"},
        {Item.ABYSSAL_GAR_AB_1, "Bifurcated Gar"},
        {Item.ABYSSAL_GAR, "Abyssal Gar"},
        {Item.ARAPAIMA_AB_1, "Broken Arapaima"},
        {Item.ARAPAIMA, "Arapaima"},
        {Item.BOREASPIS_AB_1, "Boreal Shell"},
        {Item.BOREASPIS, "Boreaspis"},
        {Item.COELACANTH_AB_1, "Shaper's Prime"},
        {Item.DEEP_FORM_AB_1, "???"},
        {Item.DUNKLEOSTEUS_AB_1, "Excoriated Fiend"},
        {Item.DUNKLEOSTEUS, "Dunkleosteus"},
        {Item.EAGLE_SHARK_AB_1, "Sanguine Shark"},
        {Item.EAGLE_SHARK, "Eagle Shark"},
        {Item.GIANT_DRAGONFISH_AB_1, "Untouchable Wyrmfish"},
        {Item.GIANT_DRAGONFISH, "Giant Dragonfish"},
        {Item.GOLIATH_TIGERFISH_AB_1, "Brute's Crux"},
        {Item.GULPER_EEL_AB_1, "Famine's End"},
        {Item.KERYGMACHELA_AB_1, "Drifting Chrysalis"},
        {Item.KERYGMACHELA, "Kerygmachela"},
        {Item.LANCETFISH_AB_1, "Silvering Lancetfish"},
        {Item.LANCETFISH, "Lancetfish"},
        {Item.MAHI_MAHI_AB_1, "Xeno Xeno"},
        {Item.MAHI_MAHI, "Mahi Mahi"},
        {Item.NAUTILUS_AB_1, "Clutching Nautilus"},
        {Item.NAUTILUS, "Nautilus"},
        {Item.NIPPONITES_AB_1, "Wretched Nipper"},
        {Item.NIPPONITES, "Nipponites"},
        {Item.OARFISH_AB_1, "Archon's Burden"},
        {Item.OPABINIA_AB_1, "Crawling Instar"},
        {Item.OPABINIA, "Opabinia"},
        {Item.OSTEOSTRACAN_AB_1, "Plated Osteostracan"},
        {Item.OSTEOSTRACAN, "Osteostracan"},
        {Item.PADDLEFISH_AB_1, "Anvilfish"},
        {Item.PADDLEFISH, "Paddlefish"},
        {Item.SAWFISH_AB_1, "Plated Barbjaw"},
        {Item.SAWFISH, "Sawfish"},
        {Item.SEA_CUCUMBER_AB_1, "Inverted Husk"},
        {Item.SEA_CUCUMBER, "Sea Cucumber"},
        {Item.SEA_SCORPION_AB_1, "Erupting Scorpion"},
        {Item.SEA_SCORPION, "Sea Scorpion"},
        {Item.SEA_SLUG_AB_1, "Mimic Slug"},
        {Item.SEA_SLUG, "Sea Slug"},
        {Item.SLEEPER_SHARK_AB_1, "Sleeper's Torment"},
        {Item.SOLLASINA_AB_1, "Vagrant Sollasina"},
        {Item.SOLLASINA, "Sollasina"},
        {Item.SWORDFISH_AB_1, "Ivory Impaler"},
        {Item.SWORDFISH, "Swordfish"},
        {Item.TRILOBITE_AB_1, "Cystic Trilobite"},
        {Item.TRILOBITE, "Trilobite"},
        {Item.TRIPOD_SPIDERFISH_AB_1, "Stalking Spiderfish"},
        {Item.TRIPOD_SPIDERFISH, "Tripod Spiderfish"},
        {Item.TULLIMONSTRUM_AB_1, "Axial Matron"},
        {Item.TULLIMONSTRUM, "Tullimonstrum"},
        {Item.VETULICOLIA_AB_1, "Unveiled Vetulicolia"},
        {Item.VETULICOLIA, "Vetulicolia"},
        {Item.XIPHACTINUS_AB_1, "Primordial Shadow"},
        {Item.XIPHACTINUS, "Xiphactinus"},
        {Item.FANGTOOTH_AB_1, "Cursed Fangtooth"},
        {Item.FANGTOOTH, "Fangtooth"},
        {Item.FIREFLY_SQUID_AB_1, "Radiant Squid"},
        {Item.FIREFLY_SQUID, "Firefly Squid"},
        {Item.FRILLED_SHARK_AB_1, "Twisted Shark"},
        {Item.FRILLED_SHARK, "Frilled Shark"},
        {Item.GAR_AB_1, "Clawfin Gar"},
        {Item.GAR_AB_2, "Grinning Gar"},
        {Item.GAR, "Gar"},
        {Item.GHOST_SHARK_AB_1, "Rapt Shark"},
        {Item.GHOST_SHARK, "Ghost Shark"},
        {Item.GIANT_AMPHIPOD_AB_1, "Ruptured Vessel"},
        {Item.GIANT_AMPHIPOD, "Giant Amphipod"},
        {Item.GLOWING_OCTOPUS_AB_1, "Medusa Octopus"},
        {Item.GLOWING_OCTOPUS, "Glowing Octopus"},
        {Item.GOLIATH_TIGERFISH, "Goliath Tigerfish"},
        {Item.EEL_AB_1, "Barbed Eel"},
        {Item.EEL_AB_2, "Host Eel"},
        {Item.EEL, "Grey Eel"},
        {Item.GREY_MULLET_AB_1, "Entwined Mullet"},
        {Item.GREY_MULLET_AB_2, "Gleaming Mullet"},
        {Item.GREY_MULLET, "Grey Mullet"},
        {Item.FLOUNDER_AB_1, "Cyclopean Flounder"},
        {Item.FLOUNDER_AB_2, "Riddled Flounder"},
        {Item.FLOUNDER, "Gulf Flounder"},
        {Item.GULPER_EEL, "Gulper Eel"},
        {Item.HAMMERHEAD_SHARK_AB_1, "Gazing Shark"},
        {Item.HAMMERHEAD_SHARK, "Hammerhead Shark"},
        {Item.LONGFIN_EEL_AB_1, "Twinned Eels"},
        {Item.LONGFIN_EEL, "Longfin Eel"},
        {Item.STOPLIGHT_LOOSEJAW_AB_1, "Perished Loosejaw"},
        {Item.STOPLIGHT_LOOSEJAW, "Loosejaw"},
        {Item.MACKEREL_AB_1, "Grotesque Mackerel"},
        {Item.MACKEREL_AB_2, "Lumpy Mackerel"},
        {Item.MACKEREL_AB_3, "Many-Eyed Mackerel"},
        {Item.MOONFISH_AB_1, "Skeletal Moonfish"},
        {Item.MOONFISH_AB_2, "Beaked Moonfish"},
        {Item.MOONFISH, "Moonfish"},
        {Item.OARFISH, "Oarfish"},
        {Item.OCEANIC_PERCH_AB_1, "Gnashing Perch"},
        {Item.OCEANIC_PERCH, "Oceanic Perch"},
        {Item.PALE_SKATE_AB_1, "Defaced Skate"},
        {Item.PALE_SKATE, "Pale Skate"},
        {Item.RATTAIL_AB_1, "Congealed Rattail"},
        {Item.RATTAIL, "Rattail"},
        {Item.RED_SNAPPER_AB_1, "Blood Snapper"},
        {Item.RED_SNAPPER_AB_2, "Latching Snapper"},
        {Item.RED_SNAPPER, "Red Snapper"},
        {Item.SAILFISH_AB_1, "Sallow Sailfish"},
        {Item.SAILFISH_AB_2, "Hooked Sailfish"},
        {Item.SAILFISH, "Sailfish"},
        {Item.SCARLET_PRAWN_AB_1, "Leeching Prawn"},
        {Item.SCARLET_PRAWN, "Scarlet Prawn"},
        {Item.SEAROBIN_AB_1, "Ossified Searobin"},
        {Item.SEAROBIN, "Armored Searobin"},
        {Item.SERGEANT_FISH_AB_1, "Vortex Interloper"},
        {Item.SERGEANT_FISH, "Sergeant Fish"},
        {Item.SNAILFISH_AB_1, "Calcified Snailfish"},
        {Item.SNAILFISH_AB_2, "Seizing Snailfish"},
        {Item.SNAILFISH, "Snailfish"},
        {Item.SNAKE_MACKEREL_AB_1, "Serpentine Mackerel"},
        {Item.SNAKE_MACKEREL_AB_2, "Tattered Mackerel"},
        {Item.SNAKE_MACKEREL, "Snake Mackerel"},
        {Item.STINGRAY_AB_1, "Shard Ray"},
        {Item.STINGRAY, "Stingray"},
        {Item.STONEFISH_AB_1, "Gelatinous Stonefish"},
        {Item.STONEFISH_AB_2, "Enthralled Stonefish"},
        {Item.STONEFISH, "Stonefish"},
        {Item.STURGEON_AB_1, "Translucent Sturgeon"},
        {Item.STURGEON, "Sturgeon"},
        {Item.SUNFISH_AB_1, "Charred Sunfish"},
        {Item.SUNFISH_AB_2, "Glaring Sunfish"},
        {Item.SUNFISH, "Ocean Sunfish"},
        {Item.TARPON_AB_1, "Blistered Tarpon"},
        {Item.TARPON, "Tarpon"},
        {Item.TIGER_MACKEREL_AB_1, "Flayed Mackerel"},
        {Item.TIGER_MACKEREL_AB_2, "Bearded Mackerel"},
        {Item.TIGER_MACKEREL, "Tiger Mackerel"},
        {Item.VIPERFISH_AB_1, "Decrepit Viperfish"},
        {Item.VIPERFISH_AB_2, "Collapsed Viperfish"},
        {Item.VIPERFISH, "Viperfish"},
        {Item.WRECKFISH_AB_1, "Shattered Wreckfish"},
        {Item.WRECKFISH_AB_2, "Bony Wreckfish"},
        {Item.WRECKFISH, "Wreckfish"},
        {Item.FLAG_1, "Hook Flag"},
        {Item.FLAG_2, "Anchor Flag"},
        {Item.FLAG_3, "Fish Flag"},
        {Item.FLAG_4, "Pirate Flag"},
        {Item.FLAG_5, "Eyes Flag"},
        {Item.FLAG_6, "Serpent Flag"},
        {Item.FLAG_7, "Ouroboros Flag"},
        {Item.GADGET_1, "Rotor Reprogrammer"},
        {Item.GADGET_2, "Reverse Gear Router"},
        {Item.GADGET_3, "Chain Optimizer"},
        {Item.GADGET_4, "Reel Accelerator"},
        {Item.GADGET_5, "Heat Sink"},
        {Item.GADGET_6, "Trawl Guidance Chip"},
        {Item.ICE_BLOCK_1, "Small Ice Block"},
        {Item.ICE_BLOCK_2, "Large Ice Block"},
        {Item.CLOTH, "Bolt of Cloth"},
        {Item.CRATE, "Ironhaven Crate"},
        {Item.LUMBER, "Lumber"},
        {Item.METAL, "Refined Metal"},
        {Item.RESEARCH_ITEM, "Research Part"},
        {Item.SCRAP, "Metal Scraps"},
        {Item.QUEST_BELT_BUCKLE, "Bronze Belt Buckle"},
        {Item.QUEST_BUILDER, "Builder"},
        {Item.QUEST_CAMERA_CASE, "Photography Equipment"},
        {Item.QUEST_CASTAWAY, "Castaway"},
        {Item.QUEST_COMPONENTS, "Prototype Parts"},
        {Item.QUEST_CORPSE, "Chunk of Flesh"},
        {Item.QUEST_DOG_TAG, "Dog Tags"},
        {Item.QUEST_DOG, "Dog"},
        {Item.QUEST_CREST, "Family Crest"},
        {Item.QUEST_FLAME, "Fathomless Flame"},
        {Item.QUEST_HERMIT, "Hermit"},
        {Item.QUEST_ICE_AXE, "Ice Axe"},
        {Item.WHOLE_ICEBREAKER, "Icebreaker"},
        {Item.QUEST_ICEBREAKER_1, "Icebreaker Plow Half 1"},
        {Item.QUEST_ICEBREAKER_2, "Icebreaker Bracing"},
        {Item.QUEST_ICEBREAKER_3, "Icebreaker Plow Half 2"},
        {Item.QUEST_ICE_SHAPER, "Ice Shaper"},
        {Item.QUEST_ICE_STONE, "Frozen Heart"},
        {Item.QUEST_MACHINE, "Repulsion Machine"},
        {Item.QUEST_MAP_1, "Scrap of Paper"},
        {Item.QUEST_MAP_2, "Small Scrap of Paper"},
        {Item.QUEST_MAP_3, "Large Scrap of Paper"},
        {Item.QUEST_MORTAR_1, "Mortar Frame"},
        {Item.QUEST_MORTAR_2, "Mortar Barrel"},
        {Item.QUEST_PACKAGE, "Small Package"},
        {Item.QUEST_PACKAGE_2, "Large Package"},
        {Item.QUEST_BAIT_1, "Pungent Bait"},
        {Item.QUEST_BAIT_2, "Fetid Bait"},
        {Item.QUEST_BAIT_3, "Reeking Bait"},
        {Item.QUEST_TABLET_1, "Stone Tablet 1"},
        {Item.QUEST_TABLET_2, "Stone Tablet 2"},
        {Item.QUEST_TABLET_3, "Stone Tablet 3"},
        {Item.QUEST_TABLET_4, "Fused Tablet"},
        {Item.HANDKERCHIEF, "Handkerchief"},
        {Item.RELIC1, "Ornate Key"},
        {Item.RELIC2, "Rusted Music Box"},
        {Item.RELIC3, "Jewel Encrusted Band"},
        {Item.RELIC4, "Shimmering Necklace"},
        {Item.RELIC5, "Antique Pocket Watch"},
        {Item.REPAIR_BOAT, "Hull Repair Kit"},
        {Item.REPAIR_PANIC, "Soothing Tea"},
        {Item.REPAIR_POT, "Harvester's Repair Pack"},
        {Item.ROT, "Rot"},
        {Item.TELEPORT_ANCHOR, "Aurous Anchor"},
        {Item.BAG_DOUBLOON, "Bag of Doubloons"},
        {Item.BIG_BAG_DOUBLOON, "Big Bag of Doubloons"},
        {Item.BROKEN_MONOCLE, "Broken Monocle"},
        {Item.BROKEN_SPECTACLES, "Broken Spectacles"},
        {Item.DOUBLOON, "Doubloon"},
        {Item.EARRING_1, "Pearl Earrings"},
        {Item.EARRING_2, "Opal Earrings"},
        {Item.EARRING_3, "Sapphire Earrings"},
        {Item.EARRING_4, "Emerald Earrings"},
        {Item.EARRING_5, "Ruby Earrings"},
        {Item.FANCY_BOOT, "Fancy Boot"},
        {Item.GOBLET, "Goblet"},
        {Item.IRON_CHAIN, "Old Iron Chain"},
        {Item.RING_1, "Worn Gold Ring"},
        {Item.RING_2, "Citrine Ring"},
        {Item.RING_3, "Opal Ring"},
        {Item.RING_4, "Sapphire Ring"},
        {Item.RING_5, "Emerald Ring"},
        {Item.RING_6, "Ruby Ring"},
        {Item.RING_7, "Signet Ring"},
        {Item.SEXTANT, "Sextant"},
        {Item.SILVER_PLATE, "Silver Plate"},
        {Item.SILVER_TRINKET, "Silver Trinket"},
        {Item.PROGRESSIVE_HULL, "Progressive Hull"}
    };

    public static Dictionary<string, Item> itemNamesReversed =
        itemNames.ToDictionary(name => name.Value, name => name.Key);

    public static string ItemToName(Item item)
    {
        return itemNames[item];
    }

    public static Item NameToItem(string itemName)
    {
        return itemNamesReversed[itemName];
    }

    public static string ItemToDredgeId(Item item)
    {
        return item.ToString().ToLower().Replace('_', '-');
    }

    public static Item DredgeIdToItem(string itemId)
    {
        var formattedString = itemId.ToUpper().Replace('-', '_');
        if (!Enum.TryParse<Item>(formattedString, true, out var item))
        {
            WinchCore.Log.Error($"Can't find item {formattedString}");
        }

        return item;
    }
}