using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using ArchipelagoDredge.Network;
using Winch.Core;

namespace ArchipelagoDredge.Game.Helpers;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public enum Location
{
    SILVER_PLATE_3 = 3,
    CLOTH_10 = 10,
    LUMBER_18 = 18,
    LUMBER_22 = 22,
    RELIC1_33 = 33,
    LUMBER_39 = 39,
    SCRAP_40 = 40,
    RING_1_44 = 44,
    QUEST_BELT_BUCKLE_46 = 46,
    IRON_CHAIN_47 = 47,
    EARRING_1_48 = 48,
    LUMBER_54 = 54,
    GOBLET_61 = 61,
    CLOTH_65 = 65,
    CLOTH_70 = 70,
    SILVER_TRINKET_76 = 76,
    SCRAP_87 = 87,
    LUMBER_107 = 107,
    SCRAP_108 = 108,
    SCRAP_109 = 109,
    SILVER_TRINKET_140 = 140,
    LUMBER_184 = 184,
    LUMBER_185 = 185,
    LUMBER_186 = 186,
    DOUBLOON_187 = 187,
    LUMBER_188 = 188,
    SCRAP_189 = 189,
    SCRAP_190 = 190,
    SCRAP_191 = 191,
    SCRAP_192 = 192,
    SCRAP_193 = 193,
    CLOTH_194 = 194,
    CLOTH_195 = 195,
    RING_2_196 = 196,
    CLOTH_197 = 197,
    METAL_198 = 198,
    METAL_199 = 199,
    RELIC2_200 = 200,
    EARRING_3_201 = 201,
    QUEST_CREST_223 = 223,
    RELIC3_224 = 224,
    RESEARCH_ITEM_336 = 336,
    BAG_DOUBLOON_337 = 337,
    RING_3_338 = 338,
    RING_4_339 = 339,
    EARRING_2_340 = 340,
    BAG_DOUBLOON_341 = 341,
    DOUBLOON_342 = 342,
    SCRAP_343 = 343,
    LUMBER_344 = 344,
    LUMBER_345 = 345,
    QUEST_MORTAR_1_413 = 413,
    QUEST_MORTAR_2_414 = 414,
    QUEST_DOG_TAG_415 = 415,
    LUMBER_417 = 417,
    LUMBER_418 = 418,
    LUMBER_419 = 419,
    LUMBER_420 = 420,
    SCRAP_421 = 421,
    SCRAP_422 = 422,
    SCRAP_423 = 423,
    CLOTH_424 = 424,
    CLOTH_425 = 425,
    METAL_426 = 426,
    EARRING_5_427 = 427,
    BROKEN_MONOCLE_428 = 428,
    RING_5_429 = 429,
    RESEARCH_ITEM_430 = 430,
    LUMBER_431 = 431,
    LUMBER_432 = 432,
    CLOTH_433 = 433,
    METAL_434 = 434,
    DOUBLOON_473 = 473,
    QUEST_TABLET_1_496 = 496,
    QUEST_TABLET_2_497 = 497,
    QUEST_TABLET_3_498 = 498,
    LUMBER_499 = 499,
    CLOTH_500 = 500,
    LUMBER_501 = 501,
    SILVER_PLATE_502 = 502,
    LUMBER_503 = 503,
    SCRAP_504 = 504,
    CLOTH_505 = 505,
    SCRAP_506 = 506,
    SILVER_PLATE_507 = 507,
    SCRAP_508 = 508,
    CLOTH_509 = 509,
    BROKEN_SPECTACLES_510 = 510,
    GOBLET_511 = 511,
    METAL_512 = 512,
    DOUBLOON_513 = 513,
    RING_6_514 = 514,
    SEXTANT_515 = 515,
    RING_5_516 = 516,
    EARRING_4_517 = 517,
    GOBLET_518 = 518,
    EARRING_5_519 = 519,
    RING_3_520 = 520,
    EARRING_4_521 = 521,
    BAG_DOUBLOON_522 = 522,
    IRON_CHAIN_523 = 523,
    IRON_CHAIN_524 = 524,
    BROKEN_MONOCLE_525 = 525,
    BROKEN_MONOCLE_526 = 526,
    SEXTANT_527 = 527,
    FANCY_BOOT_528 = 528,
    GOBLET_529 = 529,
    DOUBLOON_530 = 530,
    EARRING_3_531 = 531,
    RING_2_532 = 532,
    RESEARCH_ITEM_533 = 533,
    RESEARCH_ITEM_534 = 534,
    RESEARCH_ITEM_535 = 535,
    RESEARCH_ITEM_536 = 536,
    EARRING_3_537 = 537,
    RING_2_538 = 538,
    DOUBLOON_539 = 539,
    SEXTANT_540 = 540,
    BROKEN_SPECTACLES_541 = 541,
    CLOTH_787 = 787,
    FLAG_1_812 = 812,
    FLAG_2_813 = 813,
    FLAG_4_814 = 814,
    FLAG_5_815 = 815,
    FLAG_6_816 = 816,
    FLAG_7_817 = 817,
    QUEST_ICEBREAKER_1_818 = 818,
    QUEST_ICEBREAKER_2_819 = 819,
    QUEST_ICEBREAKER_3_820 = 820,
    QUEST_ICE_AXE_821 = 821,
    QUEST_ICE_AXE_822 = 822,
    QUEST_ICE_AXE_823 = 823,
    QUEST_ICE_AXE_824 = 824,
    QUEST_ICE_SHAPER_882 = 882,
    LUMBER_883 = 883,
    LUMBER_884 = 884,
    LUMBER_885 = 885,
    SCRAP_886 = 886,
    SCRAP_887 = 887,
    SCRAP_888 = 888,
    CLOTH_889 = 889,
    CLOTH_890 = 890,
    METAL_891 = 891,
    RING_3_892 = 892,
    TELEPORT_ANCHOR_893 = 893,
    CRATE_1050 = 1050,
    CRATE_1051 = 1051,
    CRATE_1052 = 1052,
    CRATE_1053 = 1053,
    CRATE_1054 = 1054,
    CRATE_1055 = 1055,
    CRATE_1056 = 1056,
    CRATE_1057 = 1057,
    CRATE_1058 = 1058,
    CRATE_1059 = 1059,
    CRATE_1060 = 1060,
    CRATE_1061 = 1061,
    CRATE_1062 = 1062,
    CRATE_1063 = 1063,
    CRATE_1064 = 1064,
    CRATE_1065 = 1065,
    CRATE_1066 = 1066,
    CRATE_1067 = 1067,
    CRATE_1068 = 1068,
    CRATE_1069 = 1069,
    ANCHOVY_AB_1,
    ANCHOVY,
    ANGLERFISH_AB_1,
    ANGLERFISH,
    SQUID_AB_1,
    SQUID_AB_2,
    SQUID,
    AURORA_JELLYFISH_AB_1,
    AURORA_JELLYFISH,
    BARRACUDA_AB_1,
    BARRACUDA_AB_2,
    BARRACUDA,
    BARRELEYE_AB_1,
    BARRELEYE,
    BLACK_GROUPER_AB_1,
    BLACK_GROUPER_AB_2,
    BLACK_GROUPER,
    BLACK_SEA_BASS_AB_1,
    BLACK_SEA_BASS,
    BLACKFIN_TUNA_AB_1,
    BLACKFIN_TUNA,
    BLACKMOUTH_SALMON_AB_1,
    BLACKMOUTH_SALMON,
    BLACKTIP_REEF_SHARK_AB_1,
    BLACKTIP_REEF_SHARK,
    MACKEREL,
    BRONZE_WHALER_AB_1,
    BRONZE_WHALER,
    CATFISH_AB_1,
    CATFISH,
    COD_AB_1,
    COD_AB_2,
    COD_AB_3,
    COD,
    COELACANTH,
    CONGER_EEL_AB_1,
    CONGER_EEL,
    CORAL_GROUPER_AB_1,
    CORAL_GROUPER,
    BLUE_CRAB_AB_1,
    BLUE_CRAB,
    CRAB_AB_1,
    CRAB,
    CROWN_OF_THORNS_AB_1,
    CROWN_OF_THORNS,
    DECORATOR_CRAB_AB_1,
    DECORATOR_CRAB,
    FIDDLER_CRAB_AB_1,
    FIDDLER_CRAB,
    GIANT_MUD_CRAB_AB_1,
    GIANT_MUD_CRAB,
    HORSESHOE_CRAB_AB_1,
    HORSESHOE_CRAB,
    ROCK_CRAB_AB_1,
    ROCK_CRAB,
    SPIDER_CRAB_AB_1,
    SPIDER_CRAB,
    SPINY_LOBSTER_AB_1,
    SPINY_LOBSTER,
    SQUAT_LOBSTER_AB_1,
    SQUAT_LOBSTER,
    VOLCANO_SNAIL_AB_1,
    VOLCANO_SNAIL,
    CUSK_EEL_AB_1,
    CUSK_EEL,
    DEVIL_RAY_AB_1,
    DEVIL_RAY,
    CHAR_AB_1,
    CHAR,
    COLOSSAL_SQUID_AB_1,
    COLOSSAL_SQUID,
    GOBLIN_SHARK_AB_1,
    GOBLIN_SHARK,
    ICEFISH_AB_1,
    ICEFISH_AB_2,
    ICEFISH_AB_3,
    ICEFISH,
    KING_CRAB_AB_1,
    KING_CRAB,
    LIZARDFISH_AB_1,
    LIZARDFISH,
    SEA_STARS_AB_1,
    SEA_STARS,
    SLEEPER_SHARK,
    STARGAZER_AB_1,
    STARGAZER,
    TOOTHFISH_AB_1,
    TOOTHFISH,
    WOLFFISH_AB_1,
    WOLFFISH,
    ABYSSAL_GAR_AB_1,
    ABYSSAL_GAR,
    ARAPAIMA_AB_1,
    ARAPAIMA,
    BOREASPIS_AB_1,
    BOREASPIS,
    COELACANTH_AB_1,
    DEEP_FORM_AB_1,
    DUNKLEOSTEUS_AB_1,
    DUNKLEOSTEUS,
    EAGLE_SHARK_AB_1,
    EAGLE_SHARK,
    GIANT_DRAGONFISH_AB_1,
    GIANT_DRAGONFISH,
    GOLIATH_TIGERFISH_AB_1,
    GULPER_EEL_AB_1,
    KERYGMACHELA_AB_1,
    KERYGMACHELA,
    LANCETFISH_AB_1,
    LANCETFISH,
    MAHI_MAHI_AB_1,
    MAHI_MAHI,
    NAUTILUS_AB_1,
    NAUTILUS,
    NIPPONITES_AB_1,
    NIPPONITES,
    OARFISH_AB_1,
    OPABINIA_AB_1,
    OPABINIA,
    OSTEOSTRACAN_AB_1,
    OSTEOSTRACAN,
    PADDLEFISH_AB_1,
    PADDLEFISH,
    SAWFISH_AB_1,
    SAWFISH,
    SEA_CUCUMBER_AB_1,
    SEA_CUCUMBER,
    SEA_SCORPION_AB_1,
    SEA_SCORPION,
    SEA_SLUG_AB_1,
    SEA_SLUG,
    SLEEPER_SHARK_AB_1,
    SOLLASINA_AB_1,
    SOLLASINA,
    SWORDFISH_AB_1,
    SWORDFISH,
    TRILOBITE_AB_1,
    TRILOBITE,
    TRIPOD_SPIDERFISH_AB_1,
    TRIPOD_SPIDERFISH,
    TULLIMONSTRUM_AB_1,
    TULLIMONSTRUM,
    VETULICOLIA_AB_1,
    VETULICOLIA,
    XIPHACTINUS_AB_1,
    XIPHACTINUS,
    FANGTOOTH_AB_1,
    FANGTOOTH,
    FIREFLY_SQUID_AB_1,
    FIREFLY_SQUID,
    FRILLED_SHARK_AB_1,
    FRILLED_SHARK,
    GAR_AB_1,
    GAR_AB_2,
    GAR,
    GHOST_SHARK_AB_1,
    GHOST_SHARK,
    GIANT_AMPHIPOD_AB_1,
    GIANT_AMPHIPOD,
    GLOWING_OCTOPUS_AB_1,
    GLOWING_OCTOPUS,
    GOLIATH_TIGERFISH,
    EEL_AB_1,
    EEL_AB_2,
    EEL,
    GREY_MULLET_AB_1,
    GREY_MULLET_AB_2,
    GREY_MULLET,
    FLOUNDER_AB_1,
    FLOUNDER_AB_2,
    FLOUNDER,
    GULPER_EEL,
    HAMMERHEAD_SHARK_AB_1,
    HAMMERHEAD_SHARK,
    LONGFIN_EEL_AB_1,
    LONGFIN_EEL,
    STOPLIGHT_LOOSEJAW_AB_1,
    STOPLIGHT_LOOSEJAW,
    MACKEREL_AB_1,
    MACKEREL_AB_2,
    MACKEREL_AB_3,
    MOONFISH_AB_1,
    MOONFISH_AB_2,
    MOONFISH,
    OARFISH,
    OCEANIC_PERCH_AB_1,
    OCEANIC_PERCH,
    PALE_SKATE_AB_1,
    PALE_SKATE,
    RATTAIL_AB_1,
    RATTAIL,
    RED_SNAPPER_AB_1,
    RED_SNAPPER_AB_2,
    RED_SNAPPER,
    SAILFISH_AB_1,
    SAILFISH_AB_2,
    SAILFISH,
    SCARLET_PRAWN_AB_1,
    SCARLET_PRAWN,
    SEAROBIN_AB_1,
    SEAROBIN,
    SERGEANT_FISH_AB_1,
    SERGEANT_FISH,
    SNAILFISH_AB_1,
    SNAILFISH_AB_2,
    SNAILFISH,
    SNAKE_MACKEREL_AB_1,
    SNAKE_MACKEREL_AB_2,
    SNAKE_MACKEREL,
    STINGRAY_AB_1,
    STINGRAY,
    STONEFISH_AB_1,
    STONEFISH_AB_2,
    STONEFISH,
    STURGEON_AB_1,
    STURGEON,
    SUNFISH_AB_1,
    SUNFISH_AB_2,
    SUNFISH,
    TARPON_AB_1,
    TARPON,
    TIGER_MACKEREL_AB_1,
    TIGER_MACKEREL_AB_2,
    TIGER_MACKEREL,
    VIPERFISH_AB_1,
    VIPERFISH_AB_2,
    VIPERFISH,
    WRECKFISH_AB_1,
    WRECKFISH_AB_2,
    WRECKFISH,
    ENGINE10,
    ENGINE2,
    ENGINE3,
    ENGINE4,
    ENGINE5,
    ENGINE6,
    ENGINE7,
    ENGINE8,
    ENGINE9,
    LIGHT1,
    LIGHT2,
    LIGHT3,
    LIGHT4,
    LIGHT5,
    LIGHT6,
    NET1,
    NET2,
    NET3,
    NET4,
    NET5,
    NET6,
    NET7,
    NET8,
    POT1,
    POT2,
    POT3,
    POT4,
    POT5,
    POT6,
    POT7,
    POT8,
    ROD1,
    ROD11,
    ROD12,
    ROD13,
    ROD14,
    ROD15,
    ROD16,
    ROD17,
    ROD18,
    ROD19,
    ROD2,
    ROD20,
    ROD21,
    ROD22,
    ROD23,
    ROD3,
    ROD4,
    ROD5,
    ROD6,
    ROD8,
}

public static class LocationNames
{
    public static Dictionary<Location, string> locationNames = new()
    {
        {Location.ANCHOVY_AB_1, "Anchovy King"},
        {Location.ANCHOVY, "Anchovy"},
        {Location.ANGLERFISH_AB_1, "Bursting Anglerfish"},
        {Location.ANGLERFISH, "Anglerfish"},
        {Location.SQUID_AB_1, "Brood Squid"},
        {Location.SQUID_AB_2, "Snag Squid"},
        {Location.SQUID, "Arrow Squid"},
        {Location.AURORA_JELLYFISH_AB_1, "Parhelion Jellyfish"},
        {Location.AURORA_JELLYFISH, "Aurora Jellyfish"},
        {Location.BARRACUDA_AB_1, "Savage Barracuda"},
        {Location.BARRACUDA_AB_2, "Concertina Barracuda"},
        {Location.BARRACUDA, "Barracuda"},
        {Location.BARRELEYE_AB_1, "Voideye"},
        {Location.BARRELEYE, "Barreleye"},
        {Location.BLACK_GROUPER_AB_1, "Tusked Grouper"},
        {Location.BLACK_GROUPER_AB_2, "Voltaic Grouper"},
        {Location.BLACK_GROUPER, "Black Grouper"},
        {Location.BLACK_SEA_BASS_AB_1, "Scouring Bass"},
        {Location.BLACK_SEA_BASS, "Black Sea Bass"},
        {Location.BLACKFIN_TUNA_AB_1, "Razormouth Tuna"},
        {Location.BLACKFIN_TUNA, "Blackfin Tuna"},
        {Location.BLACKMOUTH_SALMON_AB_1, "Decaying Blackmouth"},
        {Location.BLACKMOUTH_SALMON, "Blackmouth Salmon"},
        {Location.BLACKTIP_REEF_SHARK_AB_1, "Cleft-mouth Shark"},
        {Location.BLACKTIP_REEF_SHARK, "Blacktip Reef Shark"},
        {Location.MACKEREL, "Blue Mackerel"},
        {Location.BRONZE_WHALER_AB_1, "Bloodskin Shark"},
        {Location.BRONZE_WHALER, "Bronze Whaler"},
        {Location.CATFISH_AB_1, "Nightwing Catfish"},
        {Location.CATFISH, "Catfish"},
        {Location.COD_AB_1, "All-Seeing Cod"},
        {Location.COD_AB_2, "Fanged Cod"},
        {Location.COD_AB_3, "Three-Headed Cod"},
        {Location.COD, "Cod"},
        {Location.COELACANTH, "Coelacanth"},
        {Location.CONGER_EEL_AB_1, "Sprouting Eel"},
        {Location.CONGER_EEL, "Conger Eel"},
        {Location.CORAL_GROUPER_AB_1, "Consumed Grouper"},
        {Location.CORAL_GROUPER, "Coral Grouper"},
        {Location.BLUE_CRAB_AB_1, "Entangled Crab"},
        {Location.BLUE_CRAB, "Blue Crab"},
        {Location.CRAB_AB_1, "Cerebral Crab"},
        {Location.CRAB, "Common Crab"},
        {Location.CROWN_OF_THORNS_AB_1, "Crown of Nadir"},
        {Location.CROWN_OF_THORNS, "Crown of Thorns"},
        {Location.DECORATOR_CRAB_AB_1, "Cortex Decorator"},
        {Location.DECORATOR_CRAB, "Decorator Crab"},
        {Location.FIDDLER_CRAB_AB_1, "Malignant Pincer"},
        {Location.FIDDLER_CRAB, "Fiddler Crab"},
        {Location.GIANT_MUD_CRAB_AB_1, "Mire Screecher"},
        {Location.GIANT_MUD_CRAB, "Giant Mud Crab"},
        {Location.HORSESHOE_CRAB_AB_1, "Effigy Crab"},
        {Location.HORSESHOE_CRAB, "Horseshoe Crab"},
        {Location.ROCK_CRAB_AB_1, "Splintered Crab"},
        {Location.ROCK_CRAB, "Rock Crab"},
        {Location.SPIDER_CRAB_AB_1, "Umbral Puppet"},
        {Location.SPIDER_CRAB, "Spider Crab"},
        {Location.SPINY_LOBSTER_AB_1, "Imperious Lobster"},
        {Location.SPINY_LOBSTER, "Spiny Lobster"},
        {Location.SQUAT_LOBSTER_AB_1, "Sable Reacher"},
        {Location.SQUAT_LOBSTER, "Squat Lobster"},
        {Location.VOLCANO_SNAIL_AB_1, "Grasping Snail"},
        {Location.VOLCANO_SNAIL, "Volcano Snail"},
        {Location.CUSK_EEL_AB_1, "Infernal Eel"},
        {Location.CUSK_EEL, "Cusk Eel"},
        {Location.DEVIL_RAY_AB_1, "Withered Ray"},
        {Location.DEVIL_RAY, "Devil Ray"},
        {Location.CHAR_AB_1, "Bubbling Char"},
        {Location.CHAR, "Char"},
        {Location.COLOSSAL_SQUID_AB_1, "Pale Grasper"},
        {Location.COLOSSAL_SQUID, "Colossal Squid"},
        {Location.GOBLIN_SHARK_AB_1, "Grisly Shark"},
        {Location.GOBLIN_SHARK, "Goblin Shark"},
        {Location.ICEFISH_AB_1, "Fractalline Icefish"},
        {Location.ICEFISH_AB_2, "Thawed Icefish"},
        {Location.ICEFISH_AB_3, "Astral Icefish"},
        {Location.ICEFISH, "Icefish"},
        {Location.KING_CRAB_AB_1, "King's Wreath"},
        {Location.KING_CRAB, "King Crab"},
        {Location.LIZARDFISH_AB_1, "Feral Lizardfish"},
        {Location.LIZARDFISH, "Lizardfish"},
        {Location.SEA_STARS_AB_1, "Fallen Stars"},
        {Location.SEA_STARS, "Sea Stars"},
        {Location.SLEEPER_SHARK, "Sleeper Shark"},
        {Location.STARGAZER_AB_1, "Craterous Seer"},
        {Location.STARGAZER, "Stargazer"},
        {Location.TOOTHFISH_AB_1, "Bulbous Toothfish"},
        {Location.TOOTHFISH, "Toothfish"},
        {Location.WOLFFISH_AB_1, "Hinged Wolffish"},
        {Location.WOLFFISH, "Wolffish"},
        {Location.ABYSSAL_GAR_AB_1, "Bifurcated Gar"},
        {Location.ABYSSAL_GAR, "Abyssal Gar"},
        {Location.ARAPAIMA_AB_1, "Broken Arapaima"},
        {Location.ARAPAIMA, "Arapaima"},
        {Location.BOREASPIS_AB_1, "Boreal Shell"},
        {Location.BOREASPIS, "Boreaspis"},
        {Location.COELACANTH_AB_1, "Shaper's Prime"},
        {Location.DEEP_FORM_AB_1, "???"},
        {Location.DUNKLEOSTEUS_AB_1, "Excoriated Fiend"},
        {Location.DUNKLEOSTEUS, "Dunkleosteus"},
        {Location.EAGLE_SHARK_AB_1, "Sanguine Shark"},
        {Location.EAGLE_SHARK, "Eagle Shark"},
        {Location.GIANT_DRAGONFISH_AB_1, "Untouchable Wyrmfish"},
        {Location.GIANT_DRAGONFISH, "Giant Dragonfish"},
        {Location.GOLIATH_TIGERFISH_AB_1, "Brute's Crux"},
        {Location.GULPER_EEL_AB_1, "Famine's End"},
        {Location.KERYGMACHELA_AB_1, "Drifting Chrysalis"},
        {Location.KERYGMACHELA, "Kerygmachela"},
        {Location.LANCETFISH_AB_1, "Silvering Lancetfish"},
        {Location.LANCETFISH, "Lancetfish"},
        {Location.MAHI_MAHI_AB_1, "Xeno Xeno"},
        {Location.MAHI_MAHI, "Mahi Mahi"},
        {Location.NAUTILUS_AB_1, "Clutching Nautilus"},
        {Location.NAUTILUS, "Nautilus"},
        {Location.NIPPONITES_AB_1, "Wretched Nipper"},
        {Location.NIPPONITES, "Nipponites"},
        {Location.OARFISH_AB_1, "Archon's Burden"},
        {Location.OPABINIA_AB_1, "Crawling Instar"},
        {Location.OPABINIA, "Opabinia"},
        {Location.OSTEOSTRACAN_AB_1, "Plated Osteostracan"},
        {Location.OSTEOSTRACAN, "Osteostracan"},
        {Location.PADDLEFISH_AB_1, "Anvilfish"},
        {Location.PADDLEFISH, "Paddlefish"},
        {Location.SAWFISH_AB_1, "Plated Barbjaw"},
        {Location.SAWFISH, "Sawfish"},
        {Location.SEA_CUCUMBER_AB_1, "Inverted Husk"},
        {Location.SEA_CUCUMBER, "Sea Cucumber"},
        {Location.SEA_SCORPION_AB_1, "Erupting Scorpion"},
        {Location.SEA_SCORPION, "Sea Scorpion"},
        {Location.SEA_SLUG_AB_1, "Mimic Slug"},
        {Location.SEA_SLUG, "Sea Slug"},
        {Location.SLEEPER_SHARK_AB_1, "Sleeper's Torment"},
        {Location.SOLLASINA_AB_1, "Vagrant Sollasina"},
        {Location.SOLLASINA, "Sollasina"},
        {Location.SWORDFISH_AB_1, "Ivory Impaler"},
        {Location.SWORDFISH, "Swordfish"},
        {Location.TRILOBITE_AB_1, "Cystic Trilobite"},
        {Location.TRILOBITE, "Trilobite"},
        {Location.TRIPOD_SPIDERFISH_AB_1, "Stalking Spiderfish"},
        {Location.TRIPOD_SPIDERFISH, "Tripod Spiderfish"},
        {Location.TULLIMONSTRUM_AB_1, "Axial Matron"},
        {Location.TULLIMONSTRUM, "Tullimonstrum"},
        {Location.VETULICOLIA_AB_1, "Unveiled Vetulicolia"},
        {Location.VETULICOLIA, "Vetulicolia"},
        {Location.XIPHACTINUS_AB_1, "Primordial Shadow"},
        {Location.XIPHACTINUS, "Xiphactinus"},
        {Location.FANGTOOTH_AB_1, "Cursed Fangtooth"},
        {Location.FANGTOOTH, "Fangtooth"},
        {Location.FIREFLY_SQUID_AB_1, "Radiant Squid"},
        {Location.FIREFLY_SQUID, "Firefly Squid"},
        {Location.FRILLED_SHARK_AB_1, "Twisted Shark"},
        {Location.FRILLED_SHARK, "Frilled Shark"},
        {Location.GAR_AB_1, "Clawfin Gar"},
        {Location.GAR_AB_2, "Grinning Gar"},
        {Location.GAR, "Gar"},
        {Location.GHOST_SHARK_AB_1, "Rapt Shark"},
        {Location.GHOST_SHARK, "Ghost Shark"},
        {Location.GIANT_AMPHIPOD_AB_1, "Ruptured Vessel"},
        {Location.GIANT_AMPHIPOD, "Giant Amphipod"},
        {Location.GLOWING_OCTOPUS_AB_1, "Medusa Octopus"},
        {Location.GLOWING_OCTOPUS, "Glowing Octopus"},
        {Location.GOLIATH_TIGERFISH, "Goliath Tigerfish"},
        {Location.EEL_AB_1, "Barbed Eel"},
        {Location.EEL_AB_2, "Host Eel"},
        {Location.EEL, "Grey Eel"},
        {Location.GREY_MULLET_AB_1, "Entwined Mullet"},
        {Location.GREY_MULLET_AB_2, "Gleaming Mullet"},
        {Location.GREY_MULLET, "Grey Mullet"},
        {Location.FLOUNDER_AB_1, "Cyclopean Flounder"},
        {Location.FLOUNDER_AB_2, "Riddled Flounder"},
        {Location.FLOUNDER, "Gulf Flounder"},
        {Location.GULPER_EEL, "Gulper Eel"},
        {Location.HAMMERHEAD_SHARK_AB_1, "Gazing Shark"},
        {Location.HAMMERHEAD_SHARK, "Hammerhead Shark"},
        {Location.LONGFIN_EEL_AB_1, "Twinned Eels"},
        {Location.LONGFIN_EEL, "Longfin Eel"},
        {Location.STOPLIGHT_LOOSEJAW_AB_1, "Perished Loosejaw"},
        {Location.STOPLIGHT_LOOSEJAW, "Loosejaw"},
        {Location.MACKEREL_AB_1, "Grotesque Mackerel"},
        {Location.MACKEREL_AB_2, "Lumpy Mackerel"},
        {Location.MACKEREL_AB_3, "Many-Eyed Mackerel"},
        {Location.MOONFISH_AB_1, "Skeletal Moonfish"},
        {Location.MOONFISH_AB_2, "Beaked Moonfish"},
        {Location.MOONFISH, "Moonfish"},
        {Location.OARFISH, "Oarfish"},
        {Location.OCEANIC_PERCH_AB_1, "Gnashing Perch"},
        {Location.OCEANIC_PERCH, "Oceanic Perch"},
        {Location.PALE_SKATE_AB_1, "Defaced Skate"},
        {Location.PALE_SKATE, "Pale Skate"},
        {Location.RATTAIL_AB_1, "Congealed Rattail"},
        {Location.RATTAIL, "Rattail"},
        {Location.RED_SNAPPER_AB_1, "Blood Snapper"},
        {Location.RED_SNAPPER_AB_2, "Latching Snapper"},
        {Location.RED_SNAPPER, "Red Snapper"},
        {Location.SAILFISH_AB_1, "Sallow Sailfish"},
        {Location.SAILFISH_AB_2, "Hooked Sailfish"},
        {Location.SAILFISH, "Sailfish"},
        {Location.SCARLET_PRAWN_AB_1, "Leeching Prawn"},
        {Location.SCARLET_PRAWN, "Scarlet Prawn"},
        {Location.SEAROBIN_AB_1, "Ossified Searobin"},
        {Location.SEAROBIN, "Armored Searobin"},
        {Location.SERGEANT_FISH_AB_1, "Vortex Interloper"},
        {Location.SERGEANT_FISH, "Sergeant Fish"},
        {Location.SNAILFISH_AB_1, "Calcified Snailfish"},
        {Location.SNAILFISH_AB_2, "Seizing Snailfish"},
        {Location.SNAILFISH, "Snailfish"},
        {Location.SNAKE_MACKEREL_AB_1, "Serpentine Mackerel"},
        {Location.SNAKE_MACKEREL_AB_2, "Tattered Mackerel"},
        {Location.SNAKE_MACKEREL, "Snake Mackerel"},
        {Location.STINGRAY_AB_1, "Shard Ray"},
        {Location.STINGRAY, "Stingray"},
        {Location.STONEFISH_AB_1, "Gelatinous Stonefish"},
        {Location.STONEFISH_AB_2, "Enthralled Stonefish"},
        {Location.STONEFISH, "Stonefish"},
        {Location.STURGEON_AB_1, "Translucent Sturgeon"},
        {Location.STURGEON, "Sturgeon"},
        {Location.SUNFISH_AB_1, "Charred Sunfish"},
        {Location.SUNFISH_AB_2, "Glaring Sunfish"},
        {Location.SUNFISH, "Ocean Sunfish"},
        {Location.TARPON_AB_1, "Blistered Tarpon"},
        {Location.TARPON, "Tarpon"},
        {Location.TIGER_MACKEREL_AB_1, "Flayed Mackerel"},
        {Location.TIGER_MACKEREL_AB_2, "Bearded Mackerel"},
        {Location.TIGER_MACKEREL, "Tiger Mackerel"},
        {Location.VIPERFISH_AB_1, "Decrepit Viperfish"},
        {Location.VIPERFISH_AB_2, "Collapsed Viperfish"},
        {Location.VIPERFISH, "Viperfish"},
        {Location.WRECKFISH_AB_1, "Shattered Wreckfish"},
        {Location.WRECKFISH_AB_2, "Bony Wreckfish"},
        {Location.WRECKFISH, "Wreckfish"},
        {Location.ENGINE10, "Arterial Engine"},
        {Location.ENGINE2, "Rusty Outboard Engine"},
        {Location.ENGINE3, "Improved Outboard Engine"},
        {Location.ENGINE4, "Refined Outboard Engine"},
        {Location.ENGINE5, "Twin Prop Engine"},
        {Location.ENGINE6, "Jet Drive Engine"},
        {Location.ENGINE7, "Twin Jet Drive Engine"},
        {Location.ENGINE8, "Engine Stack"},
        {Location.ENGINE9, "Weak Valve Engine"},
        {Location.LIGHT1, "Cracked Bulb"},
        {Location.LIGHT2, "Cloudy Lens"},
        {Location.LIGHT3, "Halogen Spotlight"},
        {Location.LIGHT4, "Tungsten Floodlight"},
        {Location.LIGHT5, "Incandescent Array"},
        {Location.LIGHT6, "Flame of the Sky"},
        {Location.NET1, "Basic Trawl Net"},
        {Location.NET2, "Improved Trawl Net"},
        {Location.NET3, "Silt Filtering Trawl Net"},
        {Location.NET4, "Tempered Mesh Net"},
        {Location.NET5, "Large Trawl Net"},
        {Location.NET6, "Heavy-Duty Trawl Net"},
        {Location.NET7, "Radiant Trawl Net"},
        {Location.NET8, "Brittle Trawl Net"},
        {Location.POT1, "Basic Crab Pot"},
        {Location.POT2, "Efficient Crab Pot"},
        {Location.POT3, "Hardy Crab Pot"},
        {Location.POT4, "Large Crab Pot"},
        {Location.POT5, "Complex Crab Pot"},
        {Location.POT6, "Massive Crab Pot"},
        {Location.POT7, "Reinforced Crab Pot"},
        {Location.POT8, "Mouth of the Deep"},
        {Location.ROD1, "Starting Gear - Basic Fishing Pole"},
        {Location.ROD11, "Fathomless Winch"},
        {Location.ROD12, "Heat-Resistant Line"},
        {Location.ROD13, "Anti-Tangle Line"},
        {Location.ROD14, "Versatile Rod"},
        {Location.ROD15, "Harvesting Platform"},
        {Location.ROD16, "Tendon Rod"},
        {Location.ROD17, "Encrusted Talisman"},
        {Location.ROD18, "Simple Skimmer"},
        {Location.ROD19, "Sinew Spindle"},
        {Location.ROD2, "Weighted Line"},
        {Location.ROD20, "Sign of Ruin"},
        {Location.ROD21, "Custom Rod"},
        {Location.ROD22, "Barbed Ice Rod"},
        {Location.ROD23, "Glacial Lance"},
        {Location.ROD3, "Hydraulic Rod"},
        {Location.ROD4, "Flexible Fishing Pole"},
        {Location.ROD5, "Sampling Device"},
        {Location.ROD6, "Bottomless Lines"},
        {Location.ROD8, "Viscera Crane"},
        {Location.SILVER_PLATE_3, "Open Ocean - Silver Plate 1(M-10)"},
        {Location.CLOTH_10, "The Marrows - Cloth 1(J-8)"},
        {Location.LUMBER_18, "The Marrows - Lumber 1(I-6)"},
        {Location.LUMBER_22, "The Marrows - Lumber 2(K-8)"},
        {Location.RELIC1_33, "The Marrows - Ornate Key(I-7)"},
        {Location.LUMBER_39, "Open Ocean - Lumber 1(L-10)"},
        {Location.SCRAP_40, "Open Ocean - Scrap 1(K-10)"},
        {Location.RING_1_44, "The Marrows - Ring 1(K-8)"},
        {Location.QUEST_BELT_BUCKLE_46, "The Marrows - Belt Buckle(L-8)"},
        {Location.IRON_CHAIN_47, "The Marrows - Iron Chain 1(L-8)"},
        {Location.EARRING_1_48, "The Marrows - Earring 1(K-9)"},
        {Location.LUMBER_54, "Open Ocean - Lumber 2(K-10)"},
        {Location.GOBLET_61, "Open Ocean - Goblet(K-10)"},
        {Location.CLOTH_65, "Open Ocean - Cloth 1(K-10)"},
        {Location.CLOTH_70, "The Marrows - Cloth 2(L-8)"},
        {Location.SILVER_TRINKET_76, "The Marrows - Silver Trinket(I-6)"},
        {Location.SCRAP_87, "The Marrows - Scrap 1(L-8)"},
        {Location.LUMBER_107, "The Marrows - Lumber 3(K-8)"},
        {Location.SCRAP_108, "The Marrows - Scrap 2(I-6)"},
        {Location.SCRAP_109, "The Marrows - Scrap 3(J-9)"},
        {Location.SILVER_TRINKET_140, "Gale Cliffs - Silver Trinket(O-5)"},
        {Location.LUMBER_184, "Gale Cliffs - Lumber 1(M-4)"},
        {Location.LUMBER_185, "Gale Cliffs - Lumber 2(O-4)"},
        {Location.LUMBER_186, "Gale Cliffs - Lumber 3(N-3)"},
        {Location.DOUBLOON_187, "Gale Cliffs - Doubloon(O-3)"},
        {Location.LUMBER_188, "Gale Cliffs - Lumber 4(O-2)"},
        {Location.SCRAP_189, "Gale Cliffs - Scrap 1(O-4)"},
        {Location.SCRAP_190, "Gale Cliffs - Scrap 2(N-4)"},
        {Location.SCRAP_191, "Gale Cliffs - Scrap 3(N-3)"},
        {Location.SCRAP_192, "Gale Cliffs - Scrap 4(O-2)"},
        {Location.SCRAP_193, "Gale Cliffs - Scrap 5(O-4)"},
        {Location.CLOTH_194, "Gale Cliffs - Cloth 1(P-5)"},
        {Location.CLOTH_195, "Gale Cliffs - Cloth 2(O-4)"},
        {Location.RING_2_196, "Gale Cliffs - Ring 1(O-2)"},
        {Location.CLOTH_197, "Gale Cliffs - Cloth 3(O-2)"},
        {Location.METAL_198, "Gale Cliffs - Metal 1(O-4)"},
        {Location.METAL_199, "The Marrows - Metal 1(J-8)"},
        {Location.RELIC2_200, "Gale Cliffs - Musicbox(N-3)"},
        {Location.EARRING_3_201, "Gale Cliffs - Earring(N-3)"},
        {Location.QUEST_CREST_223, "Gale Cliffs - Family Crest(O-3)"},
        {Location.RELIC3_224, "Stellar Basin - Ring Relic(F-3)"},
        {Location.RESEARCH_ITEM_336, "Gale Cliffs - Research Part 1(N-4)"},
        {Location.BAG_DOUBLOON_337, "Gale Cliffs - Bag of Doubloons(N-3)"},
        {Location.RING_3_338, "Gale Cliffs - Ring 2(P-4)"},
        {Location.RING_4_339, "Stellar Basin - Ring 1(E-4)"},
        {Location.EARRING_2_340, "Stellar Basin - Earring 1(F-3)"},
        {Location.BAG_DOUBLOON_341, "Stellar Basin - Bag of Doubloons(G-5)"},
        {Location.DOUBLOON_342, "Open Ocean - Doubloon 1(I-4)"},
        {Location.SCRAP_343, "Stellar Basin - Scrap 1(G-5)"},
        {Location.LUMBER_344, "Stellar Basin - Lumber 1(D-3)"},
        {Location.LUMBER_345, "Stellar Basin - Lumber 2(E-4)"},
        {Location.QUEST_MORTAR_1_413, "Twisted Strand - Mortar 1(E-14)"},
        {Location.QUEST_MORTAR_2_414, "Twisted Strand - Mortar 2(G-13)"},
        {Location.QUEST_DOG_TAG_415, "Twisted Strand - Dog Tag 1(H-13)"},
        {Location.LUMBER_417, "Twisted Strand - Lumber 1(H-14)"},
        {Location.LUMBER_418, "Twisted Strand - Lumber 2(E-15)"},
        {Location.LUMBER_419, "Twisted Strand - Lumber 3(D-12)"},
        {Location.LUMBER_420, "Twisted Strand - Lumber 4(F-14)"},
        {Location.SCRAP_421, "Twisted Strand - Scrap 1(F-15)"},
        {Location.SCRAP_422, "Twisted Strand - Scrap 2(E-14)"},
        {Location.SCRAP_423, "Twisted Strand - Scrap 3(G-13)"},
        {Location.CLOTH_424, "Twisted Strand - Cloth 1(D-12)"},
        {Location.CLOTH_425, "Twisted Strand - Cloth 2(G-14)"},
        {Location.METAL_426, "Twisted Strand - Metal 1(E-14)"},
        {Location.EARRING_5_427, "Twisted Strand - Earring(F-14)"},
        {Location.BROKEN_MONOCLE_428, "Twisted Strand - Broken Monocle(F-13)"},
        {Location.RING_5_429, "Twisted Strand - Ring 1(E-12)"},
        {Location.RESEARCH_ITEM_430, "Stellar Basin - Research Part 1(G-2)"},
        {Location.LUMBER_431, "Stellar Basin - Lumber 3(G-2)"},
        {Location.LUMBER_432, "Stellar Basin - Lumber 4(G-2)"},
        {Location.CLOTH_433, "Stellar Basin - Cloth 1(G-2)"},
        {Location.METAL_434, "Stellar Basin - Metal 1(G-2)"},
        {Location.DOUBLOON_473, "Open Ocean - Doubloon 2(P-9)"},
        {Location.QUEST_TABLET_1_496, "Devil's Spine - Tablet 1(N-14)"},
        {Location.QUEST_TABLET_2_497, "Devil's Spine - Tablet 2(Q-13)"},
        {Location.QUEST_TABLET_3_498, "Devil's Spine - Tablet 3(P-13)"},
        {Location.LUMBER_499, "Devil's Spine - Lumber 1(O-15)"},
        {Location.CLOTH_500, "Devil's Spine - Cloth 1(N-13)"},
        {Location.LUMBER_501, "Devil's Spine - Lumber 2(P-13)"},
        {Location.SILVER_PLATE_502, "Devil's Spine - Silver Plate 1(Q-12)"},
        {Location.LUMBER_503, "Devil's Spine - Lumber 3(O-13)"},
        {Location.SCRAP_504, "Devil's Spine - Scrap 1(O-13)"},
        {Location.CLOTH_505, "Devil's Spine - Cloth 2(Q-12)"},
        {Location.SCRAP_506, "Devil's Spine - Scrap 2(P-13)"},
        {Location.SILVER_PLATE_507, "Devil's Spine - Silver Plate 2(O-15)"},
        {Location.SCRAP_508, "Devil's Spine - Scrap 2(O-13)"},
        {Location.CLOTH_509, "Devil's Spine - Cloth 3(P-14)"},
        {Location.BROKEN_SPECTACLES_510, "Devil's Spine - Broken Spectacles(O-13)"},
        {Location.GOBLET_511, "Devil's Spine - Goblet 1(Q-12)"},
        {Location.METAL_512, "Devil's Spine - Metal 1(O-14)"},
        {Location.DOUBLOON_513, "Devil's Spine - Doubloon(P-14)"},
        {Location.RING_6_514, "Devil's Spine - Ring 1(P-14)"},
        {Location.SEXTANT_515, "Devil's Spine - Sextant(O-14)"},
        {Location.RING_5_516, "Devil's Spine - Ring 2(P-15)"},
        {Location.EARRING_4_517, "Devil's Spine - Earring 1(N-14)"},
        {Location.GOBLET_518, "Devil's Spine - Goblet 2(P-12"},
        {Location.EARRING_5_519, "Devil's Spine - Earring 2(Q-14)"},
        {Location.RING_3_520, "Devil's Spine - Ring 3(P-13)"},
        {Location.EARRING_4_521, "Devil's Spine - Earring 3(P-14)"},
        {Location.BAG_DOUBLOON_522, "Open Ocean - Bag of Doubloons(K-3)"},
        {Location.IRON_CHAIN_523, "Open Ocean - Iron Chain 1(L-5)"},
        {Location.IRON_CHAIN_524, "Open Ocean - Iron Chain 2(I-10)"},
        {Location.BROKEN_MONOCLE_525, "Open Ocean - Broken Monocle 1(I-10)"},
        {Location.BROKEN_MONOCLE_526, "Open Ocean - Broken Monocle 2(I-10)"},
        {Location.SEXTANT_527, "Open Ocean - Sextant(E-10)"},
        {Location.FANCY_BOOT_528, "Open Ocean - Fancy Boot(C-7)"},
        {Location.GOBLET_529, "Open Ocean - Goblet(I-4)"},
        {Location.DOUBLOON_530, "Open Ocean - Doubloon 3(H-2)"},
        {Location.EARRING_3_531, "Open Ocean - Earring(K-2)"},
        {Location.RING_2_532, "Open Ocean - Ring 1(I-6)"},
        {Location.RESEARCH_ITEM_533, "Gale Cliffs - Research Part 2(P-2)"},
        {Location.RESEARCH_ITEM_534, "Open Ocean - Research Part 1(H-13)"},
        {Location.RESEARCH_ITEM_535, "Open Ocean - Research Part 2(K-3)"},
        {Location.RESEARCH_ITEM_536, "Stellar Basin - Research Part 2(G-4)"},
        {Location.EARRING_3_537, "Stellar Basin - Earring 2(F-4)"},
        {Location.RING_2_538, "Stellar Basin - Ring 2(E-4)"},
        {Location.DOUBLOON_539, "Stellar Basin - Doubloon(E-3)"},
        {Location.SEXTANT_540, "Stellar Basin - Sextant(F-3)"},
        {Location.BROKEN_SPECTACLES_541, "Stellar Basin - Broken Spectacles(G-4)"},
        {Location.CLOTH_787, "Open Ocean - Cloth 2(P-10)"},
        {Location.FLAG_1_812, "Open Ocean - Flag 1(H-13)"},
        {Location.FLAG_2_813, "Stellar Basin - Flag 1(G-2)"},
        {Location.FLAG_4_814, "Gale Cliffs - Flag 1(N-2)"},
        {Location.FLAG_5_815, "Devil's Spine - Flag 1(P-14)"},
        {Location.FLAG_6_816, "Open Ocean - Flag 2(I-10)"},
        {Location.FLAG_7_817, "Open Ocean - Flag 3(L-5)"},
        {Location.QUEST_ICEBREAKER_1_818, "Pale Reach - Icebreaker 1(I--4)"},
        {Location.QUEST_ICEBREAKER_2_819, "Pale Reach - Icebreaker 2(J--6)"},
        {Location.QUEST_ICEBREAKER_3_820, "Pale Reach - Icebreaker 3(F--4)"},
        {Location.QUEST_ICE_AXE_821, "Pale Reach - Ice Axe 1(G--7)"},
        {Location.QUEST_ICE_AXE_822, "Pale Reach - Ice Axe 2(K--4)"},
        {Location.QUEST_ICE_AXE_823, "Pale Reach - Ice Axe 3(F--5)"},
        {Location.QUEST_ICE_AXE_824, "Pale Reach - Ice Axe 4(J--4)"},
        {Location.QUEST_ICE_SHAPER_882, "Pale Reach - Ice Shaper(H--3)"},
        {Location.LUMBER_883, "Pale Reach - Lumber 1(H--1)"},
        {Location.LUMBER_884, "Pale Reach - Lumber 2(G--4)"},
        {Location.LUMBER_885, "Pale Reach - Lumber 3(I--5)"},
        {Location.SCRAP_886, "Pale Reach - Scrap 1(K--6)"},
        {Location.SCRAP_887, "Pale Reach - Scrap 2(F--3)"},
        {Location.SCRAP_888, "Pale Reach - Scrap 3(F--6)"},
        {Location.CLOTH_889, "Pale Reach - Cloth 1(I--6)"},
        {Location.CLOTH_890, "Pale Reach - Cloth 2(J--4)"},
        {Location.METAL_891, "Pale Reach - Metal 1(H--3)"},
        {Location.RING_3_892, "Pale Reach - Ring(J--6)"},
        {Location.TELEPORT_ANCHOR_893, "Pale Reach - Teleport Anchor(G--7)"},
        {Location.CRATE_1050, "Open Ocean - Crate 1(I-11)"},
        {Location.CRATE_1051, "Open Ocean - Crate 2(I-11)"},
        {Location.CRATE_1052, "Open Ocean - Crate 3(J-10)"},
        {Location.CRATE_1053, "Open Ocean - Crate 4(J-11)"},
        {Location.CRATE_1054, "Open Ocean - Crate 5(O-9)"},
        {Location.CRATE_1055, "Open Ocean - Crate 6(P-9)"},
        {Location.CRATE_1056, "Open Ocean - Crate 7(P-8)"},
        {Location.CRATE_1057, "Open Ocean - Crate 8(N-7)"},
        {Location.CRATE_1058, "Open Ocean - Crate 9(J-2)"},
        {Location.CRATE_1059, "Open Ocean - Crate 10(J-2)"},
        {Location.CRATE_1060, "Open Ocean - Crate 11(J-4)"},
        {Location.CRATE_1061, "Open Ocean - Crate 12(I-2)"},
        {Location.CRATE_1062, "Open Ocean - Crate 13(C-8)"},
        {Location.CRATE_1063, "Open Ocean - Crate 14(C-8)"},
        {Location.CRATE_1064, "Open Ocean - Crate 15(E-6)"},
        {Location.CRATE_1065, "Open Ocean - Crate 16(E-11)"},
        {Location.CRATE_1066, "Open Ocean - Crate 17(I-14)"},
        {Location.CRATE_1067, "Open Ocean - Crate 18(I-14)"},
        {Location.CRATE_1068, "Open Ocean - Crate 19(L-13)"},
        {Location.CRATE_1069, "Open Ocean - Crate 20(L-15)"}
    };

    public static List<Location> RelicLocations = new()
    {
        Location.RELIC1_33,
        Location.RELIC2_200,
        Location.RELIC3_224
    };

    public static Dictionary<string, Location> locationNamesReversed =
        locationNames.ToDictionary(ln => ln.Value, ln => ln.Key);

    public static Dictionary<long, Location> archipelagoIdToLocation;
    public static Dictionary<Location, long> locationToArchipelagoId;

    public static string LocationToName(Location location)
    {
        return locationNames[location];
    }

    public static Location NameToLocation(string locationName)
    {
        return locationNamesReversed[locationName];
    }

    public static string LocationToDredgeId(Location location)
    {
        return location.ToString().ToLower().Replace('_', '-');
    }

    public static Location DredgeIdToLocation(string locationId)
    {
        var formattedString = locationId.ToUpper().Replace('-', '_');
        if (!Enum.TryParse<Location>(formattedString, true, out var location))
        {
            WinchCore.Log.Error($"Can't find item {formattedString}");
        }

        return location;
    }

    public static void LoadArchipelagoIds()
    {
        archipelagoIdToLocation = new Dictionary<long, Location>();
        locationToArchipelagoId = new Dictionary<Location, long>();

        foreach (var locationName in locationNames.Select(ln => ln.Value))
        {
            var archipelagoId = ArchipelagoClient.Session.Locations.GetLocationIdFromName("DREDGE", locationName);
            //skipping "???" for now, it's deep in TIR
            if (archipelagoId == -1 && locationName != "???")
            {
                WinchCore.Log.Error($"Could not find apId for {locationName}");
                continue;
            }
            archipelagoIdToLocation.Add(archipelagoId, locationNamesReversed[locationName]);
            locationToArchipelagoId.Add(locationNamesReversed[locationName], archipelagoId);
        }
    }

    public static bool TryParseLocation(string input, out Location location)
    {
        var formattedString = input.ToUpper().Replace('-', '_');
        if (Enum.TryParse(formattedString, true, out location))
        {
            WinchCore.Log.Info($"Found Location {input} by string");
            return true;
        }

        if (int.TryParse(input, out var intValue) &&
            Enum.IsDefined(typeof(Location), intValue))
        {
            WinchCore.Log.Info($"Found Location {input} by int");
            location = (Location) intValue;
            return true;
        }

        location = default;
        return false;
    }
}